contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contactar/', views.contact_request, name='contact_request'),
    path('solicitudes/', views.contact_list, name='contact_list'),
    path('solicitudes/<int:pk>/', views.contact_detail, name='contact_detail'),
    path('success/', views.contact_success, name='contact_success'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

serca_project/urls.py
from django.contrib import admin
from django.urls import path, include # Asegúrate que 'include' esté importado
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), # Revisa esta línea
    path('obras/', include('projects.urls')),
    path('noticias/', include('A90_blog.urls')),
    path('contacto/', include('contact.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    #* mlmdflmd
    #TODO jsksdjkd
    #! jhjhj
    #? ggggg

    return render(request, 'core/home.html')

templates/core/home.html
{% extends 'base.html' %}

{% block title %}Inicio - SERCA{% endblock %}

{% block content %}
<div class="p-5 mb-2 bg-light rounded-3">
    <div class="container-fluid py-3">
        <h1 class="display-5 fw-bold">SERCA Ingeniería, Construcción y Montajes</h1>
        <p class="col-md-8 fs-4">Trabajamos día a día creando valor.</p>
        <a href="{% url 'contact:contact_request' %}" class="btn btn-custom-dark-blue btn-lg">Contáctanos !!</a>
        {% if user.is_superuser %}
        <a href="{% url 'contact:contact_list' %}" class="btn btn-custom-orange btn-lg ms-2">Ver Solicitudes</a>
        {% endif %}
    </div>
</div>

<div class="container">
    <h2 class="text-center my-4">Nuestros Servicios</h2>
    <div class="row">
        <!-- Servicio 1 -->
        <div class="col-lg-6 mb-4">
            <a href="#" class="card-link-wrapper">
                <div class="card border card-border-orange h-100">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="https://res.cloudinary.com/dtcskupwr/image/upload/v1757125757/SERCA/proyecto001_fohjxs.png" class="service-card-img rounded-start" alt="Servicio de Ingeniería">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">Proyectos de ingeniería industriales y habitacionales</h5>
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!-- Servicio 2 -->
        <div class="col-lg-6 mb-4">
            <a href="#" class="card-link-wrapper">
                <div class="card border card-border-orange h-100">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="https://res.cloudinary.com/dtcskupwr/image/upload/v1757126999/SERCA/home-1680800_1280_a2pugg.jpg" class="service-card-img rounded-start" alt="Servicio de Construcción">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">Construcciones y Remodelaciones</h5>
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!-- Servicio 3 -->
        <div class="col-lg-6 mb-4">
            <a href="#" class="card-link-wrapper">
                <div class="card border card-border-orange h-100">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="https://res.cloudinary.com/dtcskupwr/image/upload/v1757125741/SERCA/controlproject001_niqo7x.png" class="service-card-img rounded-start" alt="Servicio de Inspección">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">Control e Inspecciones de Obras</h5>
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!-- Servicio 4 -->
        <div class="col-lg-6 mb-4">
            <a href="#" class="card-link-wrapper">
                <div class="card border card-border-orange h-100">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="https://res.cloudinary.com/dtcskupwr/image/upload/v1757126559/SERCA/fontanero_reparando_136989450_vbwme0.jpg" class="service-card-img rounded-start" alt="Servicio 4">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">Emergencias Sanitarias</h5>
                                <p class="card-text">Atendemos todo tipo de emergencias sanitarias como filtraciones.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!-- Servicio 5 -->
        <div class="col-lg-6 mb-4">
            <a href="#" class="card-link-wrapper">
                <div class="card border card-border-orange">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="https://res.cloudinary.com/dtcskupwr/image/upload/v1757126690/SERCA/Emergencia-electrica-IMG_Elecampa_q5uyay.jpg" class="service-card-img rounded-start" alt="Servicio 5">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">Emergencias Eléctricas</h5>
                                <p class="card-text">Unidad certificada que atiende todo tipo de trabajos de electricidad.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>


{% endblock %}